spring:
  application:
    name: mab-user-registry
  servlet:
    multipart:
      max-file-size: 10MB   # Set your desired maximum file size here
      max-request-size: 10MB  # Set the maximum request size here if needed
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
    url: ${DB_URL:jdbc:postgresql://localhost:5434/mab_manitos_db}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8000
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
minio:
  bucket:
    name: ${MINIO_BUCKET_NAME:bmsc2023}