spring:
  application:
    name: mab-user-registry
  servlet:
    multipart:
      max-file-size: 100MB   # Set your desired maximum file size here
      max-request-size: 100MB  # Set the maximum request size here if needed
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:lEtfbOBZDtAg4v7}
    url: ${DB_URL:jdbc:postgresql://192.241.149.226:5432/db_mab}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  zipkin:
    base-url: http://192.241.149.226:9411
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://192.241.149.226:8080/realms/mab-manitos
          jwk-set-uri: http://192.241.149.226:8080/realms/mab-manitos/protocol/openid-connect/certs

server:
  port: 7000
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
minio:
  bucket:
    image: ${MINIO_BUCKET_IMAGE:mab-images}
    video: ${MINIO_BUCKET_VIDEO:mab-videos}
    documents: ${MINIO_BUCKET_DOCUMENTS:mab-documents}
    name: ${MINIO_BUCKET_PERSONAL:personal-info}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://192.241.149.226:9411/api/v2/spans

security-constraints:
  constraints:
    - auth-roles:
      - permitAll
      security-collections:
      - name: doctor
        patterns:
          - /api/v1/doctor/**
        methods:

    - auth-roles:
      - permitAll
      security-collections:
      - name: registry-patient
        patterns:
          - /api/v1/registry/patient
        methods:

    - auth-roles:
        - doctor
      security-collections:
        - name: registry-doctor
          patterns:
            - /api/v1/registry/doctor
          methods:

    - auth-roles:
        - permitAll
      security-collections:
        - name: user-exist
          patterns:
            - /api/v1/registry/user-exist
          methods:

    - auth-roles:
        - doctorJefe
      security-collections:
        - name: hospital
          patterns:
            - /api/v1/hospital
          methods:
            - POST

    - auth-roles:
        - doctorJefe
      security-collections:
        - name: hospital
          patterns:
            - /api/v1/hospital/**
          methods:
            - PUT
            - POST

    - auth-roles:
        - permitAll
      security-collections:
        - name: hospital
          patterns:
            - /api/v1/hospital/**
          methods:
            - GET
#logging:
#  pattern:
#    level: '%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]'