spring:
  application:
    name: mab-user-registry
  servlet:
    multipart:
      max-file-size: 100MB   # Set your desired maximum file size here
      max-request-size: 100MB  # Set the maximum request size here if needed
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:lEtfbOBZDtAg4v7}
    url: ${DB_URL:jdbc:postgresql://192.241.149.226:5432/db_mab}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://192.241.149.226:8080/realms/mab-manitos
          jwk-set-uri: http://192.241.149.226:8080/realms/mab-manitos/protocol/openid-connect/certs

server:
  port: 7000
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
minio:
  bucket:
    image: ${MINIO_BUCKET_IMAGE:mab-images}
    video: ${MINIO_BUCKET_VIDEO:mab-videos}
    documents: ${MINIO_BUCKET_DOCUMENTS:mab-documents}
    name: ${MINIO_BUCKET_PERSONAL:personal-info}

management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: '%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]'